
### dailyset/update

POST http://{{location}}/dailyset/update
Content-Type: application/json

{
    "ticketId": "ed920c54-ce39-4d04-a64d-5c7b8e09d5dd",
    "uid": "#school.zjut.course.201806061201",
    "type": 2,
    "sourceVersion": 0,
    "matteVersion": 0,
    "metaVersion": 0
}